#!/bin/bash -xe
make assets

rsync -essh -rv static tootstest.asd *.lisp .htaccess robots.txt templates \
	tootsville.adventuring.click:tootsville.adventuring.click/

make tootstest.cgi

scp tootstest.asd Makefile app.lisp tootsville.adventuring.click:tootsville.adventuring.click/
rsync -essh -v bin/* tootsville.adventuring.click:tootsville.adventuring.click/bin/
rsync -essh -v src/*.lisp tootsville.adventuring.click:tootsville.adventuring.click/src/

ssh tootsville.adventuring.click make -C tootsville.adventuring.click tootstest.cgi

rsync -essh -rv tootsville.org tootsvilleorg@tootsville.org:

until curl  https://tootsville.adventuring.click/tootstest/version 2>/dev/null | \
	perl -ne 'if (/build-date">(20..-..?-..?)</) {print $1}' | \
	grep $( date +%Y-%m-%d | sed -e s/-0/-/g )
do
	echo "New version not yet running (FastCGI cache?)"
	sleep 30 
done

curl https://api.rollbar.com/api/1/deploy/ \
     -F access_token=f6f4ae4d08dd415799a1ef2122fff0b0 \
     -F environment=tootstest \
     -F revision=$(git log -n 1 --pretty=format:"%H") \
     -F local_username="$(whoami)%$(hostname)"

git tag -s server-push-$(date +%Y-%m-%d-%H%M) HEAD \
    -m "Pushed to server from $(who am i)@$(hostname) at $(date); $(git status -s -uno)"

