;;; .emacs by Bruce-Robert Fenn Pocock <BRPocock@Star-Hope.org> (for
;;; myself and friends…)

;;; Copyright © 1987-2013, Bruce-Robert Fenn Pocock
;;; <brpocock@star-hope.org>

;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation; either version 3, or (at
;; your option) any later version.
;;
;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; if not, you can either send email to this
;; program's maintainer or write to: The Free Software Foundation,
;; Inc.; 675 Massachusetts Avenue; Cambridge, MA 02139, USA, or visit
;; http://www.fsf.org/
;;
(require 'package)

(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.milkbox.net/packages/")))

(package-initialize) (package-refresh-contents)
(package-install 'org)
(require 'org-install)
(require 'org-compat)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(Buffer-menu-mode-width 13)
 '(auto-revert-check-vc-info t)
 '(battery-mode-line-limit 99)
 '(byte-compile-warnings (quote (not cl-functions)))
 '(c++-mode-hook (function brp-c-hooks))
 '(c-ignore-auto-fill (quote (string cpp)))
 '(c-mode-hook (function brp-c-hooks))
 '(cal-tex-24 t)
 '(cal-tex-daily-end 21)
 '(cal-tex-daily-start 9)
 '(cal-tex-daily-string (quote (let* ((year (calendar-extract-year date)) (day (calendar-day-number date)) (days-remaining (- (calendar-day-number (list 12 31 year)) day))) (format "%d/(%d)" day days-remaining))))
 '(cal-tex-diary t)
 '(calendar-date-display-form (quote ((if dayname (concat dayname ", ")) day " " monthname ", " year)))
 '(calendar-european-date-display-form (quote ((if dayname (concat dayname ", ")) day " " monthname ", " year)))
 '(calendar-latitude 28 t)
 '(calendar-longitude -81 t)
 '(column-number-mode t)
 '(current-language-environment "UTF-8")
 '(custom-magic-show-button nil)
 '(desktop-clear-preserve-buffers (quote ("\\*scratch\\*" "\\*Messages\\*" "\\*server\\*" "\\*tramp/.+\\*" "\\*Warnings\\*" "\\*inferior-lisp.*\\*" "\\*.*repl.*\\*")))
 '(desktop-restore-eager 20)
 '(desktop-save t)
 '(desktop-save-mode t)
 '(diff-switches "-u4 -E -B -W1023")
 '(dired-dwim-target t)
 '(dired-listing-switches "-al --group-directories-first")
 '(dired-mode-hook (quote ((lambda nil (buffer-face-set (quote (:inherit default :family "Inconsolata")))))))
 '(dired-trivial-filenames "t")
 '(dired-use-ls-dired t)
 '(display-battery-mode t)
 '(display-time-mode t)
 '(ede-project-directories (quote ("/home/brpocock/Projects/violet-volts")))
 '(ediff-cleanup-hook (quote (brp-window-layout)))
 '(ediff-merge-split-window-function (lambda nil (interactive) (let (screen-effective-width (if window-system (/ (available-screen-pixel-width) (frame-char-width)) (frame-width))) (if (< screen-effective-width 150) (split-window-horizontally) (split-window-vertically)))))
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))
 '(emacs-lisp-docstring-fill-column 72)
 '(eol-mnemonic-dos "«CRLF»")
 '(eol-mnemonic-mac "«CR»")
 '(erc-public-away-p nil)
 '(erc-user-full-name (quote user-full-name))
 '(fancy-splash-image "~/Pictures/Fiach-Dubh-128×128.png")
 '(fill-nobreak-predicate (quote (fill-single-word-nobreak-p)))
 '(follow-auto t)
 '(font-use-system-font t)
 '(fringe-mode (quote (10 . 10)) nil (fringe))
 '(global-auto-revert-mode t)
 '(global-auto-revert-mode-text " ↶")
 '(global-git-gutter-mode t)
 '(global-linum-mode t)
 '(global-rainbow-delimiters-mode t)
 '(global-semantic-decoration-mode t)
 '(global-visual-line-mode t)
 '(gnus-article-button-face (quote widget-button))
 '(goto-address-mail-face (quote link))
 '(goto-address-mail-mouse-face (quote link))
 '(goto-address-url-mouse-face (quote link))
 '(grep-command "grep -nH -ri -e ")
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries (quote ((t . left) (top . left) (bottom . left) (up . left) (down . left))))
 '(indicate-empty-lines t)
 '(inferior-lisp-load-command "(progn (load \"%s\" :verbose nil :print t) (values))")
 '(ispell-complete-word-dict nil)
 '(ispell-highlight-p t)
 '(ispell-personal-dictionary "~/Documents/Dictionary")
 '(lisp-indent-function (quote common-lisp-indent-function))
 '(lunar-phase-names (quote ("New Moon" "Waxing Quarter Moon" "Full Moon" "Waning Quarter Moon")))
 '(make-pointer-invisible nil)
 '(mouse-avoidance-mode (quote animate) nil (avoid))
 '(mouse-drag-copy-region nil)
 '(mouse-sel-mode t)
 '(org-agenda-files (quote ("~/org/")))
 '(org-agenda-log-mode-items (quote (closed clock state)))
 '(org-edit-src-region-extra (quote (("#!/usr/bin/perl" "__END__" "perl"))))
 '(org-enable-fixed-width-editor nil)
 '(org-export-blocks (quote ((graph org-export-blocks-format-dot-and-eps nil) (comment org-export-blocks-format-comment t) (ditaa org-export-blocks-format-ditaa nil) (dot org-export-blocks-format-dot nil))))
 '(org-mobile-directory "/var/www/html/dav/brp-mobile-org")
 '(org-mobile-force-mobile-change t)
 '(org-mode-hook (quote (#[nil "\300\301\302\303\304$\207" [org-add-hook change-major-mode-hook org-show-block-all append local] 5] #[nil "\300\301\302\303\304$\207" [org-add-hook change-major-mode-hook org-babel-show-result-all append local] 5] org-babel-result-hide-spec org-babel-hide-all-hashes iimage-mode)))
 '(org-pretty-entities t)
 '(org-src-lang-modes (quote (("ocaml" . tuareg) ("elisp" . emacs-lisp) ("ditaa" . artist) ("asymptote" . asy) ("dot" . fundamental) ("perl" . cperl))))
 '(org-startup-folded (quote showeverything))
 '(org-support-shift-select (quote always))
 '(package-archives (quote (("gnu" . "http://elpa.gnu.org/packages/") ("marmalade" . "http://marmalade-repo.org/packages/") ("melpa" . "http://melpa.milkbox.net/packages/"))))
 '(pivotal-api-token "fae5af946b212925af606a8e2588ac6c")
 '(pp^L-^L-string "  —  —  —  —  ")
 '(pretty-control-l-mode t)
 '(safe-local-variable-values (quote ((Package . WORDNET) (Syntax . Common-lisp) (outline-minor-mode) (Package . CL-EDI) (cg . "9.0") (lisp-version . "9.0 [64-bit Linux (x86-64)] (Jun 5, 2013 12:44)") (Package . DRAKMA) (indent-tabs) (package . RFC2388) (indent-tabs-mode . NIL) (Package . MCNA\.EDI) (Syntax . COMMON-LISP) (Package . utils) (Package . SAX) (coding-system-for-write . utf-8-with-signature) (Encoding . utf-8) (readtable . runes) (Package . CXML) (Syntax . ANSI-Common-Lisp) (Package . lalr) (Base . 10) (Package . LALR) (Syntax . Common-Lisp))))
 '(save-place t nil (saveplace))
 '(scalable-fonts-allowed t)
 '(send-mail-function (quote sendmail-send-it))
 '(server-port "2773")
 '(server-use-tcp t)
 '(setq show-paren-style t)
 '(show-paren-mode t)
 '(slime-connected-hook (quote (slime-repl-connected-hook-function brp-window-layout)))
 '(solar-n-hemi-seasons (quote ("Bealtaine Equinox" "Midsummer Solstice" "Samhain Equinox" "Yule Solstice")))
 '(spice-output-local "Gnucap")
 '(spice-simulator "Gnucap")
 '(spice-waveform-viewer "Gwave")
 '(text-mode-hook (quote (turn-on-auto-fill text-mode-hook-identify)))
 '(tramp-completion-reread-directory-timeout 30)
 '(tramp-inline-compress-start-size 16384)
 '(tramp-syntax (quote url))
 '(uniquify-ask-about-buffer-names-p t)
 '(uniquify-buffer-name-style (quote post-forward) nil (uniquify))
 '(uniquify-separator " in ")
 '(user-mail-address "brpocock@Star-Hope.org")
 '(visible-bell t)
 '(visual-line-fringe-indicators (quote (left-curly-arrow right-curly-arrow)))
 '(vm-imap-account-alist (quote (("imap-ssl:imap.google.com:993:inbox:login:brpocock@mcna.net:*" "mcna") ("imap-ssl:imap.google.com:993:inbox:login:brpocock:*" "gmail"))))
 '(vm-ps-print-message-left-header (quote (list (format "(Folder “%s”)" folder-name) (format "(%d message%s printed)" mcount (if (= mcount 1) "" "s")))))
 '(vm-stunnel-program "stunnel")
 '(vm-stunnel-random-data-method (quote generate))
 '(w3m-add-referer (quote ("\\`http:" . "\\`http://\\(?:localhost\\|127\\.0\\.0\\.1\\|::1\\)/")))
 '(w3m-default-display-inline-images t)
 '(w3m-default-save-directory "~/Downloads")
 '(w3m-display-ins-del (quote fontify))
 '(w3m-use-favicon nil)
 '(wdired-allow-to-change-permissions (quote advanced))
 '(wdired-use-interactive-rename t)
 '(word-wrap t)
 '(x-stretch-cursor t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#efe9da" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :foundry "nil" :family "Cantarell"))))
 '(bold-italic ((t (:inherit (bold italic)))))
 '(buffer-menu-buffer ((t (:background "gainsboro" :foreground "navy" :weight bold))))
 '(button ((t (:inherit widget-button))))
 '(custom-button ((t (:inherit widget-button))))
 '(custom-button-mouse ((t (:inherit widget-button :background "#ccf"))))
 '(custom-button-pressed ((t (:inherit widget-button-pressed))))
 '(custom-button-pressed-unraised ((t (:inherit custom-button-unraised :foreground "magenta4"))))
 '(custom-button-unraised ((t (:background "#ccf" :foreground "black" :height 110 :family "Cantarell"))))
 '(custom-comment ((t (:height 110 :family "Cantarell"))))
 '(custom-documentation ((t (:height 1.05 :family "Cantarell"))))
 '(custom-variable-button ((t (:inherit widget-button))))
 '(custom-variable-tag ((t (:inherit custom-comment :foreground "blue1" :weight bold))))
 '(diff-added ((t (:inherit diff-changed :foreground "darkgreen"))))
 '(diff-changed ((nil (:background "lightcyan"))))
 '(diff-file-header ((t (:background "grey70" :weight bold :height 1.2 :family "Cantarell"))))
 '(diff-header ((((class color) (min-colors 88) (background light)) (:background "grey80" :height 1.1 :family "Helvetica"))))
 '(diff-indicator-added ((t (:inherit diff-added :background "green" :foreground "black" :box (:line-width 2 :color "grey75" :style released-button)))))
 '(diff-indicator-removed ((t (:inherit diff-removed :background "red" :foreground "black" :box (:line-width 2 :color "grey75" :style released-button) :strike-through nil :weight ultra-bold))))
 '(diff-nonexistent ((t (:inherit diff-file-header :background "red" :foreground "black" :height 1.2 :family "sans"))))
 '(diff-refine-change ((((class color) (min-colors 88) (background light)) (:background "#ffb" :weight bold))))
 '(diff-removed ((t (:foreground "darkred" :strike-through "red"))))
 '(dired-directory ((t (:inherit font-lock-function-name-face :foreground "blue" :height 110))))
 '(dired-flagged ((t (:strike-through "Red" :slant italic :family "Cantarell"))))
 '(dired-header ((t (:foreground "midnightblue" :underline "midnightblue" :weight bold :height 125 :family "Cantarell"))))
 '(dired-ignored ((t (:foreground "grey40" :slant italic :height 0.9 :family "Cantarell"))))
 '(dired-mark ((t (:background "#0cf"))))
 '(dired-marked ((t (:background "#0cd" :foreground "black" :weight extra-bold))))
 '(dired-perm-write ((t (:underline "orange"))))
 '(dired-symlink ((t (:inherit font-lock-keyword-face :foreground "dark cyan"))))
 '(ediff-current-diff-Ancestor ((t (:background "light blue" :foreground "Black"))))
 '(fixed-pitch ((t (:family "Inconsolata"))))
 '(font-latex-bold-face ((t (:inherit bold))))
 '(font-latex-italic-face ((t (:inherit italic))))
 '(font-latex-string-face ((t (:background "rosybrown" :foreground "black"))))
 '(font-lock-builtin-face ((t (:foreground "slateblue4" :height 1.25 :family "Cantarell"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :slant italic :weight bold))))
 '(font-lock-comment-face ((t (:background "gainsboro" :foreground "#5f615c" :slant normal :height 1.2 :family "Cantarell"))))
 '(font-lock-constant-face ((t (:foreground "dark red" :weight bold :height 1.5 :family "Cantarell"))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face :foreground "slateblue4" :background "#eee" :family "Cantarell"))))
 '(font-lock-function-name-face ((t (:foreground "dark violet" :height 1.5 :family "Cantarell"))))
 '(font-lock-keyword-face ((t (:inherit (default bold) :foreground "#432" :height 1.2 :family "Cantarell"))))
 '(font-lock-negation-char-face ((t (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#528" :height 1.2 :family "Cantarell"))))
 '(font-lock-variable-name-face ((t (:foreground "#b52" :height 1.5 :family "Cantarell"))))
 '(font-lock-warning-face ((t (:inherit error :height 1.333))))
 '(glyphless-char ((t (:height 0.75))))
 '(gnus-button ((t (:inherit widget-button))))
 '(gnus-emphasis-bold-italic ((t (:inherit (bold italic)))))
 '(highlight ((t (:background "light sky blue"))))
 '(info-title-1 ((t (:inherit info-title-2 :height 1.5))))
 '(info-title-2 ((t (:inherit info-title-3 :height 1.5))))
 '(info-title-3 ((t (:inherit info-title-4 :height 1.5))))
 '(info-title-4 ((t (:inherit default :weight bold :height 1.5 :family "Cantarell"))))
 '(info-xref ((t (:inherit link :family "Cantarell"))))
 '(isearch ((t (:background "dark orange" :foreground "white" :weight bold))))
 '(italic ((t (:slant italic :height 1.25 :family "Cantarell Italic"))))
 '(lazy-highlight ((t (:underline "orange"))))
 '(link ((t (:foreground "#204a87" :underline t :family "Cantarell"))))
 '(linum ((t (:inherit shadow))))
 '(menu ((t (:family "Cantarell"))))
 '(message-header-cc ((t (:foreground "#b52"))))
 '(message-header-name ((t (:foreground "midnightblue"))))
 '(message-header-subject ((t (:foreground "midnightblue" :weight bold :height 1.25 :family "Cantarell"))))
 '(message-header-to ((t (:foreground "#b52" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "dark violet" :weight bold))))
 '(mode-line ((t (:background "pink" :foreground "black" :box (:line-width 1 :color "violet" :style released-button)))))
 '(mode-line-buffer-id ((t (:background "pink" :foreground "black" :box (:line-width 2 :color "violet")))))
 '(mode-line-emphasis ((t (:background "violet" :weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "dark violet" :style released-button)))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#ccc" :foreground "#333" :box (:line-width -1 :style released-button) :weight light))))
 '(mouse ((t (:background "white" :foreground "midnightblue"))))
 '(nobreak-space ((t (:overline "#888"))))
 '(org-agenda-calendar-event ((t (:inherit default :height 1.1 :family "Cantarell"))))
 '(org-agenda-calendar-sexp ((t (:inherit default :background "gainsboro" :height 1.1 :family "Cantarell"))))
 '(org-document-info ((t (:foreground "midnight blue" :slant italic :height 1.1 :family "Cantarell"))))
 '(org-document-info-keyword ((t (:inherit (shadow bold)))))
 '(org-document-title ((t (:foreground "midnight blue" :weight bold :height 1.44 :family "Cantarell"))))
 '(org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t :family "Cantarell"))))
 '(org-mode-line-clock-overrun ((t (:inherit modeline :background "magenta"))) t)
 '(org-table ((t (:background "grey80" :foreground "black"))))
 '(org-tag ((t (:weight bold :family "Cantarell"))))
 '(org-verbatim ((t (:background "gainsboro" :foreground "black"))))
 '(outline-1 ((t (:inherit outline-2 :foreground "dark violet" :height 1.2))))
 '(outline-2 ((t (:inherit outline-3 :foreground "SlateBlue4" :height 1.2))))
 '(outline-3 ((t (:inherit outline-4 :foreground "dark blue" :height 1.1))))
 '(outline-4 ((t (:inherit outline-5 :foreground "dark cyan" :height 1.1))))
 '(outline-5 ((t (:inherit outline-6 :foreground "dark green" :height 1.1))))
 '(outline-6 ((t (:inherit outline-7 :foreground "brown" :height 1.1))))
 '(outline-7 ((t (:inherit outline-8 :foreground "#b52" :height 1.1))))
 '(outline-8 ((t (:foreground "dark red" :height 110 :family "Cantarell"))))
 '(pp^L-highlight ((t (:background "black" :foreground "white" :height 3.0 :width condensed))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "dark violet" :weight bold))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "dark blue" :weight bold))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "dark cyan" :weight bold))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "dark green" :weight bold))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "dark goldenrod" :weight bold))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "dark orange" :weight bold))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "dark red" :weight bold))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "black" :weight bold))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "dim grey" :weight bold))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#88090B" :slant italic :weight ultra-bold :height 1.25 :family "times"))))
 '(region ((t (:background "#0cf" :foreground "black"))))
 '(secondary-selection ((t (:background "dark cyan"))))
 '(sh-heredoc ((t (:foreground "tan4"))))
 '(shadow ((t (:foreground "grey50" :weight light))))
 '(show-paren-match ((t (:background "black" :inverse-video t :weight bold))))
 '(show-paren-mismatch ((t (:background "red" :inverse-video t))))
 '(texinfo-heading ((t (:inherit font-lock-function-name-face :foreground "midnightblue" :weight bold :height 1.5 :family "Cantarell"))))
 '(uim-candidate-selected-face ((t (:background "snow3" :foreground "blue"))) t)
 '(variable-pitch ((t (:family "Cantarell"))))
 '(w3m-anchor ((t (:inherit font-lock-comment-face :foreground "blue" :underline "blue"))))
 '(w3m-anchor-face ((t (:foreground "blue"))) t)
 '(w3m-arrived-anchor ((t (:inherit w3m-anchor-face :foreground "navy"))))
 '(w3m-bold ((t :inherit custom-comment)))
 '(w3m-current-anchor ((t (:inherit w3m-anchor-face :box (:line-width 2 :color "grey50") :underline t :weight bold))))
 '(w3m-form ((t (:inherit custom-comment :background "gainsboro" :foreground "dark green" :underline t))))
 '(w3m-form-button ((t (:inherit widget-button))))
 '(w3m-form-button-mouse ((t (:inherit custom-button-mouse))))
 '(w3m-form-button-pressed ((t (:inherit custom-button-pressed))))
 '(w3m-image ((t (:inherit custom-comment :background "black" :foreground "light Green"))))
 '(w3m-image-anchor ((t (:inherit w3m-anchor-face :background "black" :foreground "light green"))))
 '(w3m-italic ((t (:inherit custom-comment :slant italic :family "DejaVu Sans"))))
 '(w3m-underline ((t (:inherit font-lock-comment-face :foreground "black" :underline t))))
 '(warning ((t (:foreground "#ce5c00" :weight bold))))
 '(widget-button ((t (:foreground "black" :box (:line-width 2 :color "#bbb" :style released-button) :height 120 :family "Cantarell"))))
 '(widget-button-pressed ((t (:inherit widget-button-face :background "#ccc" :box (:line-width 2 :color "#bbb")))))
 '(widget-documentation ((t (:foreground "dark green" :family "Cantarell"))))
 '(widget-field ((t (:background "gainsboro" :box (:line-width 2 :color "#bbb" :style pressed-button) :height 1.24 :family "Cantarell"))))
 '(widget-inactive ((t (:inherit shadow :family "Cantarell"))))
 '(widget-single-line-field ((t (:inherit widget-field-face))))
 '(woman-bold ((t (:inherit bold :family "Cantarell"))) t))

